import type { ArchiveDraft } from "./types";

export const archiveDraft: ArchiveDraft = {
  projectId: "MODULAR-RAG-MCP-SERVER",
  scope: "Architecture First",
  languages: [
    { name: "Python", count: 122 },
    { name: "Markdown", count: 1 },
    { name: "YAML", count: 1 },
    { name: "TOML", count: 1 },
  ],
  metrics: {
    halls: 5,
    entities: 1198,
    relations: 1959,
    evidence: 1963,
  },
  halls: [
    {
      id: "architecture",
      name: "Architecture Hall",
      label: "架构展厅",
      count: 907,
      description: "Files, classes, and functions that define project structure.",
      descriptionZh: "定义项目结构的文件、类和函数。",
      dominantTypes: ["File", "Function", "Class"],
      sampleEntities: [
        "README.md",
        "src/core/query_engine/hybrid_search.py",
        "src/ingestion/pipeline.py",
      ],
      risk: "High coupling surface",
      riskZh: "高耦合变更面",
    },
    {
      id: "retrieval",
      name: "Retrieval Hall",
      label: "检索展厅",
      count: 26,
      description: "Entities related to retrieval behavior and configuration.",
      descriptionZh: "与检索行为和配置相关的实体。",
      dominantTypes: ["Retriever", "Import", "Config"],
      sampleEntities: [
        "dense_retriever.create_dense_retriever",
        "sparse_retriever.create_sparse_retriever",
        "query_engine.hybrid_search",
      ],
      risk: "Core behavior path",
      riskZh: "核心行为路径",
    },
    {
      id: "configuration",
      name: "Configuration Hall",
      label: "配置展厅",
      count: 12,
      description: "Configuration keys and files extracted from project settings.",
      descriptionZh: "从项目设置中抽取的配置键和配置文件。",
      dominantTypes: ["Config", "YAML"],
      sampleEntities: ["llm", "embedding", "vector_store"],
      risk: "Environment sensitive",
      riskZh: "环境敏感区域",
    },
    {
      id: "concept",
      name: "Concept Hall",
      label: "概念展厅",
      count: 39,
      description: "Concepts and headings found in project documentation.",
      descriptionZh: "项目文档中发现的概念和标题。",
      dominantTypes: ["Concept", "Markdown"],
      sampleEntities: ["Modular RAG MCP Server", "项目概述", "核心能力一览"],
      risk: "Docs drift watch",
      riskZh: "文档漂移观察点",
    },
    {
      id: "dependency",
      name: "Dependency Hall",
      label: "依赖展厅",
      count: 240,
      description: "Imported dependencies referenced by source files.",
      descriptionZh: "源码文件引用的导入依赖。",
      dominantTypes: ["Import", "Package"],
      sampleEntities: ["sys", "pathlib.Path", "src.core.settings"],
      risk: "Upgrade surface",
      riskZh: "升级影响面",
    },
  ],
  relations: [
    {
      id: "r1",
      source: "README.md",
      target: "Modular RAG MCP Server",
      type: "MENTIONS",
      hall: "concept",
      evidenceIds: ["ev_01e018078824"],
    },
    {
      id: "r2",
      source: "query_processor.py",
      target: "hybrid_search.py",
      type: "CALLS",
      hall: "retrieval",
      evidenceIds: ["ev_arch", "ev_retrieval"],
    },
    {
      id: "r3",
      source: "settings.yaml",
      target: "vector_store",
      type: "CONFIGURES",
      hall: "configuration",
      evidenceIds: ["ev_retrieval"],
    },
    {
      id: "r4",
      source: "pipeline.py",
      target: "document_chunker.py",
      type: "USES",
      hall: "architecture",
      evidenceIds: ["ev_arch"],
    },
    {
      id: "r5",
      source: "server.py",
      target: "query_project_twin",
      type: "EXPOSES",
      hall: "architecture",
      evidenceIds: ["ev_arch"],
    },
    {
      id: "r6",
      source: "dense_retriever.py",
      target: "openai_embedding.py",
      type: "DEPENDS_ON",
      hall: "dependency",
      evidenceIds: ["ev_retrieval"],
    },
  ],
  evidenceCards: [
    {
      id: "ev_01e018078824",
      title: "Heading: Modular RAG MCP Server",
      titleZh: "标题：Modular RAG MCP Server",
      sourcePath: "README.md",
      sourceType: "markdown",
      snippet: "# Modular RAG MCP Server",
      snippetZh: "# Modular RAG MCP Server",
      lineRange: "L1",
      confidence: 1,
      hall: "concept",
    },
    {
      id: "ev_7fda0e00fd5f",
      title: "Heading: 项目概述",
      titleZh: "标题：项目概述",
      sourcePath: "README.md",
      sourceType: "markdown",
      snippet: "## 项目概述",
      snippetZh: "## 项目概述",
      lineRange: "L19",
      confidence: 1,
      hall: "concept",
    },
    {
      id: "ev_retrieval",
      title: "Retrieval configuration",
      titleZh: "检索配置",
      sourcePath: "config/settings.yaml",
      sourceType: "config",
      snippet: "retrieval, embedding, vector_store, and reranker settings are loaded before query execution.",
      snippetZh: "查询执行前会加载 retrieval、embedding、vector_store 和 reranker 等设置。",
      lineRange: "Config",
      confidence: 0.92,
      hall: "retrieval",
    },
    {
      id: "ev_arch",
      title: "Query engine composition",
      titleZh: "查询引擎组合方式",
      sourcePath: "src/core/query_engine/hybrid_search.py",
      sourceType: "code",
      snippet: "Dense and sparse retrievers are fused before reranking and response assembly.",
      snippetZh: "密集检索和稀疏检索会先融合，再进入重排和回答组装流程。",
      lineRange: "Module",
      confidence: 0.88,
      hall: "architecture",
    },
  ],
};
